###
GET http://localhost:9090/api/members/

###
GET  http://localhost:9090/api/boards/error

###
GET http://localhost:9090/api/boards/a

###
POST http://localhost:9090/api/boards
Content-Type: application/json

{
  "title": "aaaa",
  "content": "test2222"
}