server:
  port: 9090

spring:
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:tcp://localhost/~/vue
      username: sa
      password: 1

common: prod-common
test: prod-test