server:
  port: 8080

spring:
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:tcp://localhost/~/vue
      username: sa
      password: 1

common: dev-common
test: dev-test